#
# Copyright (c) 2018 MotoNetwork.
# Idealizado por ClhoeMiss e DevNatan.
#
reward:
  money: 15000.0
  commands:
    - "spawner give %player CuboDeMagma 10000"
questions-and-answers:
  0:
    question: "Quem foi que fez este plugin?"
    answers:
      - "NT"
      - "mito"