main: ${project.parent.groupId}.bolao.Bolao
name: ${project.artifactId}
version: ${project.version}
author: DevNatan
depend: [Vault]
website: https://github.com/MotoCrack/Events4M
description: ${project.description}

commands:
  bolao:
    description: Apostar no evento bolao.
    usage: /bolao (argumentos)

permissions:
  events4m.bolao.iniciar:
    description: Permitir um jogador iniciar o evento Bolao.